Vault:
  use: true
  back-price: 100
  spawn-price: 0
  hub-price: 0
  unit: 'dollar'

deleteBackLocation:
  onBackCommand: true
  onPlayerQuit: true
  onPlayerKick: true

WarpRiddenEntity: true

#Messages

TeleportPlayer: '&6%target &aにテレポートしました。'
MakePlayerTeleport: '&6%player &aを&6 %target &aにテレポートさせました。'
MakePlayerSendReq: '&6%player &aのリクエストを&6 %target &aにを送らせました。'
TeleportWorld: '&6%world &aにテレポートしました。'
TeleportSpawn: '&aスポーン地点にテレポートしました。'
SetSpawn: '&aスポーン地点を設定しました。'
DeleteSpawn: '&aスポーン地点を削除しました。'
TeleportOtherSpawn: '&6%world &aのスポーン地点にテレポートしました。'
TeleportHub: '&6Hubにテレポートしました。'
SetHub: '&aHubを設定しました。'
DeleteHub: '&aHubを削除しました。'
TeleportWarp: '&a%warpにテレポートしました。'
SetWarp: '&a%warpを設定しました。'
SetPrice: '&a%warpの価格を%price%unitに設定しました。'
AddMember: '&a%warpのメンバーに%memberを追加しました。'
DeleteWarp: '&a%warpを削除しました。'
ChatClear: '&2チャットが &3%player &2によって綺麗にされました。'
PaidPrice: '&a%price%unit支払いました。'
WarpSignCreate: '&aワープ看板を作成しました。'
WarpSignBreak: '&aワープ看板を削除しました。'
Reload: '&aコンフィグをリロードしました。'
ConvertFile: '&aエンコード形式をencodeに変更しました。'

NoSpawn: '&cスポーン地点が設定されていません。'
NoHub: '&cHub地点が設定されていません。'
NoWarp: '&cそのワープ地点は設定されていません。'
ExistWarp: '&cそのワープ地点は既に作成されています。'
PlayerOnlyCmd: '&cプレイヤーのみ実行が可能です。'
PrivateOnly: '&cメンバーの追加はプライベートのワープのみ追加できます。'
HaveAlreadyBeenMember: '&c既に%warpのメンバーです。'
PlayerFailed: '&cプレイヤーが見つかりませんでした。'
PlayerHasnotPlayedBefore: '&cそのプレイヤーはこのサーバーに参加したことがありません。'
NotSpecifyPlayer: '&cコマンドの後にプレイヤーを指定して下さい。'
WorldFailed: '&c指定されたワールドは存在しません。'
NoPerms: '&c権限がありません。'
NoMoney: '&cお金が足りません。(%price%unit 必要です。)'
NoDeathLocation: '&cあなたは一回も死んでいません。'
WrongUsage: '&cコマンドの使用方法を確認して下さい。'
Error: '&cエラーが発生しました。管理人に報告して下さい。'

Prefix: '&e[Teleport]'